# Generated by Django 4.2.16 on 2025-05-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
