# Generated by Django 4.2.16 on 2025-05-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_exercise_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseprogress',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
